### ISSUE TITLE
Exception when adding a user collaboration

### ISSUE THREAD

**Issue by leio10** [podemos-info/decidim-module-crowdfundings#38]
# This is a Bug Report

#### :tophat: Description
* What went wrong?
Exception when adding a user collaboration.
* What did you expect should have happened?

* What was the config you used?
* What stacktrace or error message from your provider did you see?

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***:
* ***Browser & version***: Firefox (last)
* ***Screenshot***:
![imagen](https://user-images.githubusercontent.com/453545/33893531-ead2edd0-df5b-11e7-9c64-3c6757dcc4ec.png)
* ***Error messages***: Unknown validator: 'IbanValidator'
* ***URL to reproduce the error***: /assemblies/[assembly]/f/[feature_id]/collaborations/[collaboration_id]/user_collaborations/confirm

**Comment by jsperezg** [comment]
I can't reproduce this issue on my development environment. Please check that you've followed the instructions in the Readme.md and you've included both gems in your app:

## Installation
Add the following lines to your application's Gemfile:

```ruby
gem 'decidim-collaborations'
gem 'iban_bic'
```

**Comment by leio10** [comment]
Sorry, I didn't add the gem to the Gemfile, but I'm not sure if this should be that way. Maybe we should add a `require "iban_bic"` to the engine file, as said [here](https://stackoverflow.com/questions/5159607/rails-engine-gems-dependencies-how-to-load-them-into-the-application). What do you think?

**Comment by jsperezg** [comment]
Definetivelly looks much better. I will prepare a PR
